//
// Copyright (C) YuqiaoZhang(HanetakaChou)
//
// This program is free software: you can redistribute it and/or modify
// it under the terms of the GNU Lesser General Public License as published
// by the Free Software Foundation, either version 3 of the License, or
// (at your option) any later version.
//
// This program is distributed in the hope that it will be useful,
// but WITHOUT ANY WARRANTY; without even the implied warranty of
// MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
// GNU Lesser General Public License for more details.
//
// You should have received a copy of the GNU Lesser General Public License
// along with this program.  If not, see <https://www.gnu.org/licenses/>.
//

#ifndef _BRX_MOTION_VIDEO_DETECTOR_H_
#define _BRX_MOTION_VIDEO_DETECTOR_H_ 1

enum
{
    INTERNAL_VIDEO_DETECTOR_FACE_SKELETON_JOINT_NAME_HEAD = 0,
    INTERNAL_VIDEO_DETECTOR_FACE_SKELETON_JOINT_NAME_RIGHT_EYE = 1,
    INTERNAL_VIDEO_DETECTOR_FACE_SKELETON_JOINT_NAME_LEFT_EYE = 2,
    INTERNAL_VIDEO_DETECTOR_FACE_SKELETON_JOINT_NAME_COUNT = 3
};

enum
{
    INTERNAL_VIDEO_DETECTOR_POSE_SKELETON_JOINT_NAME_UPPER_BODY_2 = 0,
    INTERNAL_VIDEO_DETECTOR_POSE_SKELETON_JOINT_NAME_RIGHT_ARM = 1,
    INTERNAL_VIDEO_DETECTOR_POSE_SKELETON_JOINT_NAME_RIGHT_ELBOW = 2,
    INTERNAL_VIDEO_DETECTOR_POSE_SKELETON_JOINT_NAME_RIGHT_WRIST = 3,
    INTERNAL_VIDEO_DETECTOR_POSE_SKELETON_JOINT_NAME_RIGHT_INDEX = 4,
    INTERNAL_VIDEO_DETECTOR_POSE_SKELETON_JOINT_NAME_LEFT_ARM = 5,
    INTERNAL_VIDEO_DETECTOR_POSE_SKELETON_JOINT_NAME_LEFT_ELBOW = 6,
    INTERNAL_VIDEO_DETECTOR_POSE_SKELETON_JOINT_NAME_LEFT_WRIST = 7,
    INTERNAL_VIDEO_DETECTOR_POSE_SKELETON_JOINT_NAME_LEFT_INDEX = 8,
    INTERNAL_VIDEO_DETECTOR_POSE_SKELETON_JOINT_NAME_LOWER_BODY = 9,
    INTERNAL_VIDEO_DETECTOR_POSE_SKELETON_JOINT_NAME_RIGHT_LEG = 10,
    INTERNAL_VIDEO_DETECTOR_POSE_SKELETON_JOINT_NAME_RIGHT_KNEE = 11,
    INTERNAL_VIDEO_DETECTOR_POSE_SKELETON_JOINT_NAME_RIGHT_ANKLE = 12,
    INTERNAL_VIDEO_DETECTOR_POSE_SKELETON_JOINT_NAME_RIGHT_TOE_TIP = 13,
    INTERNAL_VIDEO_DETECTOR_POSE_SKELETON_JOINT_NAME_LEFT_LEG = 14,
    INTERNAL_VIDEO_DETECTOR_POSE_SKELETON_JOINT_NAME_LEFT_KNEE = 15,
    INTERNAL_VIDEO_DETECTOR_POSE_SKELETON_JOINT_NAME_LEFT_ANKLE = 16,
    INTERNAL_VIDEO_DETECTOR_POSE_SKELETON_JOINT_NAME_LEFT_TOE_TIP = 17,
    INTERNAL_VIDEO_DETECTOR_POSE_SKELETON_JOINT_NAME_COUNT = 18
};

#endif
