//
// Copyright (C) YuqiaoZhang(HanetakaChou)
//
// This program is free software: you can redistribute it and/or modify
// it under the terms of the GNU Lesser General Public License as published
// by the Free Software Foundation, either version 3 of the License, or
// (at your option) any later version.
//
// This program is distributed in the hope that it will be useful,
// but WITHOUT ANY WARRANTY; without even the implied warranty of
// MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
// GNU Lesser General Public License for more details.
//
// You should have received a copy of the GNU Lesser General Public License
// along with this program.  If not, see <https://www.gnu.org/licenses/>.
//

#ifndef _BRX_MOTION_VIDEO_DETECTOR_H_
#define _BRX_MOTION_VIDEO_DETECTOR_H_ 1

#include "../include/brx_motion.h"
#if defined(__GNUC__)
// GCC or CLANG
#pragma GCC diagnostic push
#pragma GCC diagnostic ignored "-Wunknown-pragmas"
#include <DirectXMath.h>
#pragma GCC diagnostic pop
#elif defined(_MSC_VER)
// MSVC or CLANG-CL
#include <DirectXMath.h>
#else
#error Unknown Compiler
#endif

enum
{
    INTERNAL_VIDEO_DETECTOR_FACE_MORPH_JOINT_NAME_RIGHT_EYE = 0,
    INTERNAL_VIDEO_DETECTOR_FACE_MORPH_JOINT_NAME_LEFT_EYE = 1,
    INTERNAL_VIDEO_DETECTOR_FACE_MORPH_JOINT_NAME_COUNT = 2
};

enum
{
    INTERNAL_VIDEO_DETECTOR_HAND_SKELETON_JOINT_NAME_RIGHT_WRIST = 0,
    INTERNAL_VIDEO_DETECTOR_HAND_SKELETON_JOINT_NAME_RIGHT_THUMB_CMC = 1,
    INTERNAL_VIDEO_DETECTOR_HAND_SKELETON_JOINT_NAME_RIGHT_THUMB_MCP = 2,
    INTERNAL_VIDEO_DETECTOR_HAND_SKELETON_JOINT_NAME_RIGHT_THUMB_IP = 3,
    INTERNAL_VIDEO_DETECTOR_HAND_SKELETON_JOINT_NAME_RIGHT_THUMB_TIP = 4,
    INTERNAL_VIDEO_DETECTOR_HAND_SKELETON_JOINT_NAME_RIGHT_INDEX_FINGER_MCP = 5,
    INTERNAL_VIDEO_DETECTOR_HAND_SKELETON_JOINT_NAME_RIGHT_INDEX_FINGER_PIP = 6,
    INTERNAL_VIDEO_DETECTOR_HAND_SKELETON_JOINT_NAME_RIGHT_INDEX_FINGER_DIP = 7,
    INTERNAL_VIDEO_DETECTOR_HAND_SKELETON_JOINT_NAME_RIGHT_INDEX_FINGER_TIP = 8,
    INTERNAL_VIDEO_DETECTOR_HAND_SKELETON_JOINT_NAME_RIGHT_MIDDLE_FINGER_MCP = 9,
    INTERNAL_VIDEO_DETECTOR_HAND_SKELETON_JOINT_NAME_RIGHT_MIDDLE_FINGER_PIP = 10,
    INTERNAL_VIDEO_DETECTOR_HAND_SKELETON_JOINT_NAME_RIGHT_MIDDLE_FINGER_DIP = 11,
    INTERNAL_VIDEO_DETECTOR_HAND_SKELETON_JOINT_NAME_RIGHT_MIDDLE_FINGER_TIP = 12,
    INTERNAL_VIDEO_DETECTOR_HAND_SKELETON_JOINT_NAME_RIGHT_RING_FINGER_MCP = 13,
    INTERNAL_VIDEO_DETECTOR_HAND_SKELETON_JOINT_NAME_RIGHT_RING_FINGER_PIP = 14,
    INTERNAL_VIDEO_DETECTOR_HAND_SKELETON_JOINT_NAME_RIGHT_RING_FINGER_DIP = 15,
    INTERNAL_VIDEO_DETECTOR_HAND_SKELETON_JOINT_NAME_RIGHT_RING_FINGER_TIP = 16,
    INTERNAL_VIDEO_DETECTOR_HAND_SKELETON_JOINT_NAME_RIGHT_PINKY_MCP = 17,
    INTERNAL_VIDEO_DETECTOR_HAND_SKELETON_JOINT_NAME_RIGHT_PINKY_PIP = 18,
    INTERNAL_VIDEO_DETECTOR_HAND_SKELETON_JOINT_NAME_RIGHT_PINKY_DIP = 19,
    INTERNAL_VIDEO_DETECTOR_HAND_SKELETON_JOINT_NAME_RIGHT_PINKY_TIP = 20,
    INTERNAL_VIDEO_DETECTOR_HAND_SKELETON_JOINT_NAME_LEFT_WRIST = 21,
    INTERNAL_VIDEO_DETECTOR_HAND_SKELETON_JOINT_NAME_LEFT_THUMB_CMC = 22,
    INTERNAL_VIDEO_DETECTOR_HAND_SKELETON_JOINT_NAME_LEFT_THUMB_MCP = 23,
    INTERNAL_VIDEO_DETECTOR_HAND_SKELETON_JOINT_NAME_LEFT_THUMB_IP = 24,
    INTERNAL_VIDEO_DETECTOR_HAND_SKELETON_JOINT_NAME_LEFT_THUMB_TIP = 25,
    INTERNAL_VIDEO_DETECTOR_HAND_SKELETON_JOINT_NAME_LEFT_INDEX_FINGER_MCP = 26,
    INTERNAL_VIDEO_DETECTOR_HAND_SKELETON_JOINT_NAME_LEFT_INDEX_FINGER_PIP = 27,
    INTERNAL_VIDEO_DETECTOR_HAND_SKELETON_JOINT_NAME_LEFT_INDEX_FINGER_DIP = 28,
    INTERNAL_VIDEO_DETECTOR_HAND_SKELETON_JOINT_NAME_LEFT_INDEX_FINGER_TIP = 29,
    INTERNAL_VIDEO_DETECTOR_HAND_SKELETON_JOINT_NAME_LEFT_MIDDLE_FINGER_MCP = 30,
    INTERNAL_VIDEO_DETECTOR_HAND_SKELETON_JOINT_NAME_LEFT_MIDDLE_FINGER_PIP = 31,
    INTERNAL_VIDEO_DETECTOR_HAND_SKELETON_JOINT_NAME_LEFT_MIDDLE_FINGER_DIP = 32,
    INTERNAL_VIDEO_DETECTOR_HAND_SKELETON_JOINT_NAME_LEFT_MIDDLE_FINGER_TIP = 33,
    INTERNAL_VIDEO_DETECTOR_HAND_SKELETON_JOINT_NAME_LEFT_RING_FINGER_MCP = 34,
    INTERNAL_VIDEO_DETECTOR_HAND_SKELETON_JOINT_NAME_LEFT_RING_FINGER_PIP = 35,
    INTERNAL_VIDEO_DETECTOR_HAND_SKELETON_JOINT_NAME_LEFT_RING_FINGER_DIP = 36,
    INTERNAL_VIDEO_DETECTOR_HAND_SKELETON_JOINT_NAME_LEFT_RING_FINGER_TIP = 37,
    INTERNAL_VIDEO_DETECTOR_HAND_SKELETON_JOINT_NAME_LEFT_PINKY_MCP = 38,
    INTERNAL_VIDEO_DETECTOR_HAND_SKELETON_JOINT_NAME_LEFT_PINKY_PIP = 39,
    INTERNAL_VIDEO_DETECTOR_HAND_SKELETON_JOINT_NAME_LEFT_PINKY_DIP = 40,
    INTERNAL_VIDEO_DETECTOR_HAND_SKELETON_JOINT_NAME_LEFT_PINKY_TIP = 41,
    INTERNAL_VIDEO_DETECTOR_HAND_SKELETON_JOINT_NAME_COUNT = 42
};

enum
{
    INTERNAL_VIDEO_DETECTOR_FACE_SKELETON_JOINT_NAME_HEAD = 0,
    INTERNAL_VIDEO_DETECTOR_FACE_SKELETON_JOINT_NAME_COUNT = 1
};

enum
{
    INTERNAL_VIDEO_DETECTOR_POSE_SKELETON_JOINT_NAME_UPPER_BODY_2 = 0,
    INTERNAL_VIDEO_DETECTOR_POSE_SKELETON_JOINT_NAME_RIGHT_ARM = 1,
    INTERNAL_VIDEO_DETECTOR_POSE_SKELETON_JOINT_NAME_RIGHT_ELBOW = 2,
    INTERNAL_VIDEO_DETECTOR_POSE_SKELETON_JOINT_NAME_RIGHT_WRIST = 3,
    INTERNAL_VIDEO_DETECTOR_POSE_SKELETON_JOINT_NAME_LEFT_ARM = 4,
    INTERNAL_VIDEO_DETECTOR_POSE_SKELETON_JOINT_NAME_LEFT_ELBOW = 5,
    INTERNAL_VIDEO_DETECTOR_POSE_SKELETON_JOINT_NAME_LEFT_WRIST = 6,
    INTERNAL_VIDEO_DETECTOR_POSE_SKELETON_JOINT_NAME_LOWER_BODY = 7,
    INTERNAL_VIDEO_DETECTOR_POSE_SKELETON_JOINT_NAME_RIGHT_LEG = 8,
    INTERNAL_VIDEO_DETECTOR_POSE_SKELETON_JOINT_NAME_RIGHT_KNEE = 9,
    INTERNAL_VIDEO_DETECTOR_POSE_SKELETON_JOINT_NAME_RIGHT_ANKLE = 10,
    INTERNAL_VIDEO_DETECTOR_POSE_SKELETON_JOINT_NAME_RIGHT_TOE_TIP = 11,
    INTERNAL_VIDEO_DETECTOR_POSE_SKELETON_JOINT_NAME_LEFT_LEG = 12,
    INTERNAL_VIDEO_DETECTOR_POSE_SKELETON_JOINT_NAME_LEFT_KNEE = 13,
    INTERNAL_VIDEO_DETECTOR_POSE_SKELETON_JOINT_NAME_LEFT_ANKLE = 14,
    INTERNAL_VIDEO_DETECTOR_POSE_SKELETON_JOINT_NAME_LEFT_TOE_TIP = 15,
    INTERNAL_VIDEO_DETECTOR_POSE_SKELETON_JOINT_NAME_COUNT = 16
};

class internal_brx_motion_video_detector : public brx_motion_video_detector
{
public:
    virtual double get_delta_time() const = 0;
    virtual DirectX::XMFLOAT4 const get_face_morph_joint_weight(uint32_t face_index, BRX_MOTION_SKELETON_JOINT_NAME skeleton_joint_name) const = 0;
    virtual DirectX::XMFLOAT3 const *get_pose_skeleton_joint_translation(uint32_t pose_index, BRX_MOTION_SKELETON_JOINT_NAME skeleton_joint_name) const = 0;
    virtual DirectX::XMFLOAT4 const *get_face_skeleton_joint_rotation(uint32_t face_index, BRX_MOTION_SKELETON_JOINT_NAME skeleton_joint_name) const = 0;
    virtual DirectX::XMFLOAT3 const *get_hand_skeleton_joint_translation(uint32_t hand_index, BRX_MOTION_SKELETON_JOINT_NAME skeleton_joint_name) const = 0;
    virtual void retain() = 0;
    virtual void release() = 0;
};

#endif
